### ISSUE TITLE
Difficulty resetting to 0 after death.

### ISSUE THREAD

**Issue by mortuusars** [GrigLog/Harder#2]
- Increase difficulty normally or with /harder set [1/2] <playername>
- /harder get <playername> - result: [1/2]
- die
- /harder get <playername>
- 0.

Version: 1.18.2 - 1.2

**Comment by GrigLog** [comment]
Damn I was sure I had checked death...

**Comment by GrigLog** [comment]
Thanks for the report, mod was simply useless without that
